tasks:
   - name: aws-cli
     env:
       AWS_CLI_AUTO_PROMPT: on-partial
     init: |
       cd /workspace
       curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
       unzip awscli-bundle.zip
       sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws 
       cd $THEIA_WORKSPACE_ROOT


vscode:
  extensions:
    - 42Crunch.vscode-openapi